# Custom Language File for Launcher Customizer

[ejs.app]
title = "스타빌리지"

[ejs.landing]
mediaGitHubURL = "https://github.com/mchlauncher/STARVILLAGE"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/pBwHw3BkwR"
mediaSoopURL = "#"
mediaChzzkURL = "#"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/mchlauncher/STARVILLAGE"
supportLink = "https://github.com/mchlauncher/STARVILLAGE/issues"

[ejs.welcome]
welcomeHeader = "스타빌리지"
welcomeDescription = ""
welcomeDescCTA = "[계속] 버튼을 눌러 계속 진행하여 주세요."